# Generated by Django 6.0 on 2025-12-31 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=8)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('nivelogrado', models.CharField(max_length=50)),
                ('seccion', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio_lectivo', models.CharField(max_length=10)),
                ('fecha_matricula', models.DateField(auto_now_add=True)),
                ('matricula', models.DecimalField(decimal_places=2, max_digits=8)),
                ('mobiliario', models.DecimalField(decimal_places=2, max_digits=8)),
                ('papeleria', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tecnologia', models.DecimalField(decimal_places=2, max_digits=8)),
                ('seguro_escolar', models.DecimalField(decimal_places=2, max_digits=8)),
                ('colegiatura_mensual', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiante.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Colegiatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pagada', models.BooleanField(default=False)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiante.matricula')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recibo_numero', models.CharField(max_length=20, unique=True)),
                ('fecha_pago', models.DateField(auto_now_add=True)),
                ('concepto', models.CharField(max_length=50)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('responsable', models.CharField(max_length=100)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiante.estudiante')),
            ],
        ),
    ]
