# Generated by Django 6.0 on 2025-12-31 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='concepto',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='monto',
        ),
        migrations.CreateModel(
            name='PendientePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=50)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pagado', models.BooleanField(default=False)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('recargo', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiante.estudiante')),
            ],
        ),
        migrations.AddField(
            model_name='pago',
            name='pendientes',
            field=models.ManyToManyField(related_name='pagos', to='estudiante.pendientepago'),
        ),
    ]
