# Generated by Django 6.0 on 2026-01-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0002_remove_pago_concepto_remove_pago_monto_pendientepago_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='pendientepago',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pendientepago',
            name='concepto',
            field=models.CharField(max_length=100),
        ),
    ]
