# Generated by Django 6.0 on 2026-01-02 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0003_reporte_pendientepago_fecha_vencimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='anio_lectivo',
            field=models.IntegerField(),
        ),
    ]
